name: Backend CI

on:
  push:
    branches: [main, develop, 3-base-de-datos-modelado-relacional-y-capa-de-cache, yandrisRivera/Frontend-Login]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/**'

jobs:
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: backend

      - name: Generate Prisma Client
        run: pnpm exec prisma generate
        working-directory: backend

      - name: Run Lint
        run: pnpm run lint
        working-directory: backend

      - name: Run Tests
        run: pnpm run test
        working-directory: backend

      - name: Run Build
        run: pnpm run build
        working-directory: backend
